apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: run-every-minute-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: minute-run
            image: busybox
          restartPolicy: OnFailure
