apiVersion: v1
kind: Pod
metadata:
  name: pod-for-config-secret
spec:
  securityContext:
    fsGroup: 2000
  containers:
  - name: pod-for-config-secret
    image: linuxacademycontent/candy-service:1
    volumeMounts:
      - name: config-volume
        mountPath: /etc/pod-for-config-secret
    env:
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-password
          key: password
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes:
  - name: config-volume
    configMap:
      name: basic-config
